auto_luffy/auto_luffy/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from app01.views import user
from app01.views import host
from app01.views import account

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^login/$', account.login, name='login'),
    url(r'^logout/$', account.logout, name='logout'),

    url(r'^index/$', account.index, name='index'),

    url(r'^user/list/$', user.user_list, name='user_list'),
    url(r'^user/add/$', user.user_add, name='user_add'),
    url(r'^user/edit/(?P<pk>\d+)/$', user.user_edit, name='user_edit'),
    url(r'^user/del/(?P<pk>\d+)/$', user.user_del, name='user_del'),
    url(r'^user/reset/password/(?P<pk>\d+)/$', user.user_reset_pwd, name='user_reset_pwd'),

    url(r'^host/list/$', host.host_list, name='host_list'),
    url(r'^host/add/$', host.host_add, name='host_add'),
    url(r'^host/edit/(?P<pk>\d+)/$', host.host_edit, name='host_edit'),
    url(r'^host/del/(?P<pk>\d+)/$', host.host_del, name='host_del'),

    url(r'^rbac/', include(('rbac.urls', "rbac"), namespace='rbac')),

]

django-rbac/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from app01.views import user
from app01.views import host
from app01.views import account

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^login/$', account.login, name='login'),
    url(r'^logout/$', account.logout, name='logout'),

    url(r'^index/$', account.index, name='index'),

    url(r'^user/list/$', user.user_list, name='user_list'),
    url(r'^user/add/$', user.user_add, name='user_add'),
    url(r'^user/edit/(?P<pk>\d+)/$', user.user_edit, name='user_edit'),
    url(r'^user/del/(?P<pk>\d+)/$', user.user_del, name='user_del'),
    url(r'^user/reset/password/(?P<pk>\d+)/$', user.user_reset_pwd, name='user_reset_pwd'),

    url(r'^host/list/$', host.host_list, name='host_list'),
    url(r'^host/add/$', host.host_add, name='host_add'),
    url(r'^host/edit/(?P<pk>\d+)/$', host.host_edit, name='host_edit'),
    url(r'^host/del/(?P<pk>\d+)/$', host.host_del, name='host_del'),

    url(r'^rbac/', include(('rbac.urls', "rbac"), namespace='rbac')),

]

rbac/urls.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
from django.conf.urls import url, include
from django.contrib import admin
from rbac.views import role
from rbac.views import user
from rbac.views import menu

urlpatterns = [

    url(r'^role/list/$', role.role_list, name='role_list'),  # rbac:role_list
    url(r'^role/add/$', role.role_add, name='role_add'),  # rbac:role_add
    url(r'^role/edit/(?P<pk>\d+)/$', role.role_edit, name='role_edit'),  # rbac:role_edit
    url(r'^role/del/(?P<pk>\d+)/$', role.role_del, name='role_del'),  # rbac:role_del

    # url(r'^user/list/$', user.user_list, name='user_list'),
    # url(r'^user/add/$', user.user_add, name='user_add'),
    # url(r'^user/edit/(?P<pk>\d+)/$', user.user_edit, name='user_edit'),  # rbac:user_edit
    # url(r'^user/del/(?P<pk>\d+)/$', user.user_del, name='user_del'),
    # url(r'^user/reset/password/(?P<pk>\d+)/$', user.user_reset_pwd, name='user_reset_pwd'),

    url(r'^menu/list/$', menu.menu_list, name='menu_list'),
    url(r'^menu/add/$', menu.menu_add, name='menu_add'),
    url(r'^menu/edit/(?P<pk>\d+)/$', menu.menu_edit, name='menu_edit'),
    url(r'^menu/del/(?P<pk>\d+)/$', menu.menu_del, name='menu_del'),

    url(r'^second/menu/add/(?P<menu_id>\d+)$', menu.second_menu_add, name='second_menu_add'),
    url(r'^second/menu/edit/(?P<pk>\d+)/$', menu.second_menu_edit, name='second_menu_edit'),
    url(r'^second/menu/del/(?P<pk>\d+)/$', menu.second_menu_del, name='second_menu_del'),

    url(r'^permission/add/(?P<second_menu_id>\d+)/$', menu.permission_add, name='permission_add'),
    url(r'^permission/edit/(?P<pk>\d+)/$', menu.permission_edit, name='permission_edit'),
    url(r'^permission/del/(?P<pk>\d+)/$', menu.permission_del, name='permission_del'),

    url(r'^multi/permissions/$', menu.multi_permissions, name='multi_permissions'),
    url(r'^multi/permissions/del/(?P<pk>\d+)/$', menu.multi_permissions_del, name='multi_permissions_del'),

    url(r'^distribute/permissions/$', menu.distribute_permissions, name='distribute_permissions'),

]

app01/models.py
from django.db import models
from rbac.models import UserInfo as RbacUserInfo


class Department(models.Model):
    """
    部门表
    """
    title = models.CharField(verbose_name='部门', max_length=32)

    def __str__(self):
        return self.title


class UserInfo(RbacUserInfo):
    """
    用户表
    """
    phone = models.CharField(verbose_name='联系方式', max_length=32)
    level_choices = (
        (1, 'T1'),
        (2, 'T2'),
        (3, 'T3'),
    )
    level = models.IntegerField(verbose_name='级别', choices=level_choices)

    depart = models.ForeignKey(verbose_name='部门', to='Department',on_delete=models.CASCADE)


class Host(models.Model):
    """
    主机表
    """
    hostname = models.CharField(verbose_name='主机名', max_length=32)
    ip = models.GenericIPAddressField(verbose_name='IP', protocol='both')
    depart = models.ForeignKey(verbose_name='归属部门', to='Department',on_delete=models.CASCADE)

    def __str__(self):
        return self.hostname

app01/forms/host.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-

from django import forms
from app01 import models


class HostModelForm(forms.ModelForm):
    class Meta:
        model = models.Host
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super(HostModelForm, self).__init__(*args, **kwargs)
        # 统一给ModelForm生成字段添加样式
        for name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

app01/forms/user.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
from django import forms
from django.core.exceptions import ValidationError

from app01 import models


class UserModelForm(forms.ModelForm):
    confirm_password = forms.CharField(label='确认密码')

    class Meta:
        model = models.UserInfo
        fields = ['name', 'password', 'confirm_password', 'email', 'phone', 'level', 'depart', 'roles']

    def __init__(self, *args, **kwargs):
        super(UserModelForm, self).__init__(*args, **kwargs)
        # 统一给ModelForm生成字段添加样式
        for name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

    def clean_confirm_password(self):
        """
        检测密码是否一致
        :return:
        """
        password = self.cleaned_data['password']
        confirm_password = self.cleaned_data['confirm_password']
        if password != confirm_password:
            raise ValidationError('两次密码输入不一致')
        return confirm_password


class UpdateUserModelForm(forms.ModelForm):
    class Meta:
        model = models.UserInfo
        exclude = ['password',]

    def __init__(self, *args, **kwargs):
        super(UpdateUserModelForm, self).__init__(*args, **kwargs)
        # 统一给ModelForm生成字段添加样式
        for name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ResetPasswordUserModelForm(forms.ModelForm):
    confirm_password = forms.CharField(label='确认密码')

    class Meta:
        model = models.UserInfo
        fields = ['password', 'confirm_password']

    def __init__(self, *args, **kwargs):
        super(ResetPasswordUserModelForm, self).__init__(*args, **kwargs)
        # 统一给ModelForm生成字段添加样式
        for name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

    def clean_confirm_password(self):
        """
        检测密码是否一致
        :return:
        """
        password = self.cleaned_data['password']
        confirm_password = self.cleaned_data['confirm_password']
        if password != confirm_password:
            raise ValidationError('两次密码输入不一致')
        return confirm_password

app01/views/account.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
from django.shortcuts import render, redirect
from app01 import models
from rbac.service.init_permission import init_permission


def login(request):
    if request.method == 'GET':
        return render(request, 'login.html')

    user = request.POST.get('username')
    pwd = request.POST.get('password')

    user_object = models.UserInfo.objects.filter(name=user, password=pwd).first()
    if not user_object:
        return render(request, 'login.html', {'error': '用户名或密码错误'})

    # 用户权限信息的初始化
    init_permission(user_object, request)

    return redirect('/index/')


def logout(request):
    """
    注销
    :param request:
    :return:
    """
    request.session.delete()
    return redirect('/login/')


def index(request):
    """
    首页
    :param request:
    :return:
    """
    return render(request, 'index.html')

app01/views/host.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
from django.shortcuts import render, redirect, HttpResponse
from app01 import models
from app01.forms.host import HostModelForm
from rbac.service.urls import memory_reverse


def host_list(request):
    host_queryset = models.Host.objects.all()
    return render(request, 'host_list.html', {"host_queryset": host_queryset})


def host_add(request):
    if request.method == 'GET':
        form = HostModelForm()
        return render(request, 'rbac/change.html', {'form': form})

    form = HostModelForm(data=request.POST)
    if form.is_valid():
        form.save()
        return redirect(memory_reverse(request, 'host_list'))

    return render(request, 'rbac/change.html', {'form': form})


def host_edit(request, pk):
    obj = models.Host.objects.filter(id=pk).first()
    if not obj:
        return HttpResponse('主机不存在')
    if request.method == 'GET':
        form = HostModelForm(instance=obj)
        return render(request, 'rbac/change.html', {'form': form})

    form = HostModelForm(instance=obj, data=request.POST)
    if form.is_valid():
        form.save()
        return redirect(memory_reverse(request, 'host_list'))

    return render(request, 'rbac/change.html', {'form': form})


def host_del(request, pk):
    origin_url = memory_reverse(request, 'host_list')
    if request.method == 'GET':
        return render(request, 'rbac/delete.html', {'cancel': origin_url})

    models.Host.objects.filter(id=pk).delete()
    return redirect(origin_url)

app01/views/user.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
from django.shortcuts import render, redirect, HttpResponse
from app01 import models
from app01.forms.user import UserModelForm, UpdateUserModelForm, ResetPasswordUserModelForm
from rbac.service.urls import memory_reverse


def user_list(request):
    """
    用户列表
    :param request:
    :return:
    """

    user_queryset = models.UserInfo.objects.all()

    return render(request, 'user_list.html', {'user_queryset': user_queryset})


def user_add(request):
    """
    添加角色
    :param request:
    :return:
    """
    if request.method == 'GET':
        form = UserModelForm()
        return render(request, 'rbac/change.html', {'form': form})

    form = UserModelForm(data=request.POST)
    if form.is_valid():
        form.save()
        return redirect(memory_reverse(request, 'user_list'))

    return render(request, 'rbac/change.html', {'form': form})


def user_edit(request, pk):
    """
    编辑用户
    :param request:
    :param pk: 要修改的用户ID
    :return:
    """
    obj = models.UserInfo.objects.filter(id=pk).first()
    if not obj:
        return HttpResponse('用户不存在')
    if request.method == 'GET':
        form = UpdateUserModelForm(instance=obj)
        return render(request, 'rbac/change.html', {'form': form})

    form = UpdateUserModelForm(instance=obj, data=request.POST)
    if form.is_valid():
        form.save()
        return redirect(memory_reverse(request, 'user_list'))

    return render(request, 'rbac/change.html', {'form': form})


def user_reset_pwd(request, pk):
    """
    重置密码
    :param request:
    :param pk:
    :return:
    """
    obj = models.UserInfo.objects.filter(id=pk).first()
    if not obj:
        return HttpResponse('用户不存在')
    if request.method == 'GET':
        form = ResetPasswordUserModelForm()
        return render(request, 'rbac/change.html', {'form': form})

    form = ResetPasswordUserModelForm(instance=obj, data=request.POST)
    if form.is_valid():
        form.save()
        return redirect(memory_reverse(request, 'user_list'))

    return render(request, 'rbac/change.html', {'form': form})


def user_del(request, pk):
    """
    删除用户
    :param request:
    :param pk:
    :return:
    """
    origin_url = memory_reverse(request, 'user_list')
    if request.method == 'GET':
        return render(request, 'rbac/delete.html', {'cancel': origin_url})

    models.UserInfo.objects.filter(id=pk).delete()
    return redirect(origin_url)

app01/templates/host_list.html
{% extends 'layout.html' %}
{% load rbac %}

{% block content %}
    <div class="luffy-container">
        <div class="btn-group" style="margin: 5px 0">

            {% if request|has_permission:'host_add' %}
                <a class="btn btn-default" href="{% memory_url request 'host_add' %}">
                    <i class="fa fa-plus-square" aria-hidden="true"></i> 添加主机
                </a>
            {% endif %}

        </div>
        <table class="table table-bordered table-hover">
            <thead>
            <tr>
                <th>主机名</th>
                <th>IP</th>
                <th>部门</th>
                {% if request|has_permission:'host_edit' or request|has_permission:'host_del' %}
                    <th>操作</th>
                {% endif %}

            </tr>
            </thead>
            <tbody>
            {% for row in host_queryset %}
                <tr>
                    <td>{{ row.hostname }}</td>
                    <td>{{ row.ip }}</td>
                    <td>{{ row.depart.title }}</td>
                    {% if request|has_permission:'host_edit' or request|has_permission:'host_del' %}
                        <td>
                            {% if request|has_permission:'host_edit' %}
                                <a style="color: #333333;" href="{% memory_url request 'host_edit' pk=row.id %}">
                                    <i class="fa fa-edit" aria-hidden="true"></i></a>
                            {% endif %}
                            {% if request|has_permission:'host_del' %}
                                <a style="color: #d9534f;" href="{% memory_url request 'host_del' pk=row.id %}"><i
                                        class="fa fa-trash-o"></i></a>
                            {% endif %}
                        </td>
                    {% endif %}
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

{% endblock %}

app01/templates/index.html
{% extends 'layout.html' %}

{% block content %}
    <div class="luffy-container">
        <h3>欢迎使用XX管理系统</h3>
    </div>

{% endblock %}

app01/templates/login.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'plugins/bootstrap/css/bootstrap.css' %}">
</head>
<body>

<div style="width: 500px;margin: 0 auto;margin-top: 100px;">
    <form class="form-horizontal" method="post">
        {% csrf_token %}

        <div class="form-group">
            <label for="user" class="col-sm-2 control-label">用户名</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="user" name="username">
            </div>
        </div>
        <div class="form-group">
            <label for="pwd" class="col-sm-2 control-label">密码</label>
            <div class="col-sm-10">
                <input type="password" class="form-control" id="pwd" name="password">
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-primary">登 录</button>
                <span style="color: red">{{ error }}</span>
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <p>用户名：武沛齐   密码:123 </p>
            </div>
        </div>

    </form>

</div>
</body>
</html>

app01/templates/user_list.html
{% extends 'layout.html' %}
{% load rbac %}

{% block content %}
    <div class="luffy-container">
        <div class="btn-group" style="margin: 5px 0">
            {% if request|has_permission:'user_add' %}
                <a class="btn btn-default" href="{% memory_url request 'user_add' %}">
                    <i class="fa fa-plus-square" aria-hidden="true"></i> 添加用户
                </a>
            {% endif %}

        </div>
        <table class="table table-bordered table-hover">
            <thead>
            <tr>
                <th>用户名</th>
                <th>邮箱</th>
                <th>级别</th>
                <th>部门</th>
                <th>手机</th>
                {% if request|has_permission:'user_reset_pwd' %}
                    <th>重置密码</th>
                {% endif %}

                {% if request|has_permission:'user_edit' or request|has_permission:'user_del' %}
                    <th>操作</th>
                {% endif %}

            </tr>
            </thead>
            <tbody>
            {% for row in user_queryset %}
                <tr>
                    <td>{{ row.name }}</td>
                    <td>{{ row.email }}</td>
                    <td>{{ row.get_level_display }}</td>
                    <td>{{ row.depart.title }}</td>
                    <td>{{ row.phone }}</td>
                    {% if request|has_permission:'user_reset_pwd' %}
                        <td>
                            <a href="{% memory_url request 'user_reset_pwd' pk=row.id %}">重置密码</a>
                        </td>
                    {% endif %}

                    {% if request|has_permission:'user_edit' or request|has_permission:'user_del' %}
                        <td>
                            {% if request|has_permission:'user_edit' %}
                                <a style="color: #333333;" href="{% memory_url request 'user_edit' pk=row.id %}">
                                    <i class="fa fa-edit" aria-hidden="true"></i></a>
                            {% endif %}
                            {% if request|has_permission:'user_del' %}
                                <a style="color: #d9534f;" href="{% memory_url request 'user_del' pk=row.id %}"><i
                                        class="fa fa-trash-o"></i></a>
                            {% endif %}
                        </td>
                    {% endif %}
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

{% endblock %}